# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128, verbose_name='文件名')),
                ('size', models.IntegerField(verbose_name='文件大小')),
                ('status', models.IntegerField(verbose_name='完成状态')),
                ('path', models.CharField(max_length=64, verbose_name='文件路径')),
                ('md5', models.CharField(max_length=64, verbose_name='md5码')),
                ('upload', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, verbose_name='用户密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='所属用户'),
        ),
    ]
